development:
  adapter: postgresql
  database: template_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: template_test
  pool: 5
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: template_production
  username: template
  password:
